INSERT INTO CATEGORY (NAME,DESCRIPTION) values ('CATEGORIA 1','DESC 1'); 
INSERT INTO CATEGORY (NAME,DESCRIPTION) values ('CATEGORIA 2','DESC 2'); 
INSERT INTO CATEGORY (NAME,DESCRIPTION) values ('CATEGORIA 3','DESC 3'); 
INSERT INTO CATEGORY (NAME,DESCRIPTION) values ('CATEGORIA 4','DESC 4'); 
INSERT INTO CATEGORY (NAME,DESCRIPTION) values ('CATEGORIA 5','DESC 5'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 1',1,1,'HACIENDA 1','DESC 1'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 2',2,1,'HACIENDA 2','DESC 2'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 3',3,2,'HACIENDA 3','DESC 3'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 4',4,2,'HACIENDA 4','DESC 4');  
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 5',5,2,'HACIENDA 5','DESC 5');  
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 6',6,3,'HACIENDA 6','DESC 6'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 7',7,3,'HACIENDA 7','DESC 7'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 8',8,4,'HACIENDA 8','DESC 8'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 9',9,5,'HACIENDA 9','DESC 9'); 
INSERT INTO FARM (address,extension,category_id,name,description) values ('DIRECCION 10',10,5,'HACIENDA 10','DESC 10');
INSERT INTO client (age,email,name,password) VALUES(41,'sandrajohannaduran@hotmail.com','SANDRA JOHANNA DURAN CHACON','37861963');
INSERT INTO client (age,email,name,password) VALUES(43,'taniheg104@xhyemail.com','JESUS ERNESTO LOPEZ TELLEZ','13563084');
INSERT INTO client (age,email,name,password) VALUES(44,'luisa.lievano98@gmail.com','CESAR AUGUSTO LIEVANO ','79763896');
INSERT INTO client (age,email,name,password) VALUES(26,'lizeth86@gmail.com','LIZETH YURANY PABON PARRA','1026587153');
INSERT INTO client (age,email,name,password) VALUES(22,'lady.perez-p@uniminuto.edu.co','LADY ESMERALDA PEREZ PEREZ','1002462429');
INSERT INTO client (age,email,name,password) VALUES(29,'JFFORERO59@GMAIL.COM','YEFERSON STIVEN FORERO ARDILA','1022988145');
INSERT INTO client (age,email,name,password) VALUES(50,'mariaplazas43@gmail.com','MARIA YAKELINE PLAZAS GRANADOS','52039543');
INSERT INTO client (age,email,name,password) VALUES(29,'pedroantoniocardenas792@gmail.com','PEDRO ANTONIO CARDENAS BRIÑEZ','1105684792');
INSERT INTO client (age,email,name,password) VALUES(21,'aleja1207mfc@gmail.com','MARIA ALEJANDRA MURILLO ORTIZ','1001096426');
INSERT INTO client (age,email,name,password) VALUES(27,'julianc.ramirez.valenzuela@gmail.com','JULIAN CAMILO RAMIREZ VALENZUELA','1107089742');
INSERT INTO client (age,email,name,password) VALUES(33,'NATALIACUADROG@GMAIL.COM','NEIDY NATHALIA CUADRADO GARCIA','1054091696');
INSERT INTO client (age,email,name,password) VALUES(30,'alopezgonzalez1@gmail.com','CAMILO ANDRES GONZALEZ LOPEZ','1052399367');
INSERT INTO client (age,email,name,password) VALUES(28,'erica78978@hotmail.com','ERICA LORENA VALDERRAMA CONTRERAS','1073168285');
INSERT INTO client (age,email,name,password) VALUES(21,'yesicasanta54@gmail.com','YESICA YULIANA SANTA QUESADA','1006149751');
INSERT INTO client (age,email,name,password) VALUES(26,'yessicapayoma@misena.edu.co','YESSICA FERNANDA PAYOMA CARVAJAL','1082216428');
INSERT INTO client (age,email,name,password) VALUES(58,'JUANKLOM64@HOTMAIL.COM','JUAN CARLOS LOZANO MEDINA','12126551');
INSERT INTO client (age,email,name,password) VALUES(22,'dvfer1692@gmail.com','YULY FERNANDA DUQUE VALDES','1007204081');
INSERT INTO client (age,email,name,password) VALUES(41,'lilikheme@gmail.com','LILI SORAIDA BECERRA MEDINA','46453427');
INSERT INTO client (age,email,name,password) VALUES(26,'josegalvis@gmail.com','JOSE ALEXANDER GALVIS CONTRERAS','1098826926');
INSERT INTO client (age,email,name,password) VALUES(21,'CROZOFELIPE96@GMAIL.COM','ARNOLD ROSO OSPINA','1000124182');
INSERT INTO client (age,email,name,password) VALUES(21,'camilosada15@gmail.com','JUAN CAMILO LOSADA LOPEZ','1001046376');
INSERT INTO client (age,email,name,password) VALUES(21,'brayannicolaycalderongordillo@gmail.com','BRAYAN NICOLAY CALDERON GORDILLO','1000003630');
INSERT INTO client (age,email,name,password) VALUES(27,'belinda066@hotmail.com','BELINDA MARIANA FERNANDEZ PALACIO','1124031869');
INSERT INTO client (age,email,name,password) VALUES(38,'arto0590@hotmail.co','MARIO HUMBERTO MIRANDA MORENO','13275539');
INSERT INTO client (age,email,name,password) VALUES(34,'camilarqm@gmail.com','CAMILA ANDREA RODRIGUEZ QUINCHANEGUA','1022349375');
INSERT INTO client (age,email,name,password) VALUES(22,'acdc31422@gmail.com','ANGIE DANIELA CASALLAS CASTILLO','1000734072');
INSERT INTO client (age,email,name,password) VALUES(63,'fcrockfabian@gmail.com','PEDRO ANTONIO CHACON SUAREZ','19430915');
INSERT INTO client (age,email,name,password) VALUES(29,'lau_diaz_85@hotmail.com','JEISSON DAVID MORALES RAMIREZ','1014249200');
INSERT INTO client (age,email,name,password) VALUES(53,'LAURISPATICO@GMAIL.COM','LAURA PATRICIA BASTIDAS ENRIQUEZ','30744193');
INSERT INTO client (age,email,name,password) VALUES(55,'DONETIERNA@GMAIL.COM','DONELCY JUDITH MONTAÑO CANTILLO','30773645');
INSERT INTO client (age,email,name,password) VALUES(39,'CAROIBARTREBOL@GMAIL.COM','CAROL ANDREA IBARRA CABRERA','59311650');
INSERT INTO client (age,email,name,password) VALUES(35,'JAVIERAMOS11@GMAIL.COM','HEBERTH JAVIER RAMOS VANEGAS','1069722563');
INSERT INTO client (age,email,name,password) VALUES(32,'carmonagloria451@hotmail.com','GLORIA PATRICIA CARMONA GARCIA','1102831058');
INSERT INTO client (age,email,name,password) VALUES(23,'DAJUALPA@HOTMAIL.COM','DANIELA ALEXANDRA MARTINEZ PINEDA','1032507469');
INSERT INTO client (age,email,name,password) VALUES(61,'dayanaelenacampo@gmail.com','HORACIO MIGUEL CAMPO ARIZA','18938474');
INSERT INTO client (age,email,name,password) VALUES(25,'derlimarun@gmail.com','LEIDY PAOLA FLOREZ ROJAS','1002595074');
INSERT INTO client (age,email,name,password) VALUES(45,'ingridalexa14@hotmail.com','SILVERIO DE JESUS SANABRIA CEPEDA','79887137');
INSERT INTO client (age,email,name,password) VALUES(29,'jonathan-hes@hormail.com','JONATHAN HENRIQUEZ MEZA','1023926210');
INSERT INTO client (age,email,name,password) VALUES(49,'delacruzbrenda48@gmail.com','EBER JACINTO CAICEDO ','5366197');
INSERT INTO client (age,email,name,password) VALUES(45,'luisafernandacalderon1978@gmail.com','LUISA FERNANDA CALDERON ','1113039402');
INSERT INTO client (age,email,name,password) VALUES(33,'henrycarvajal96@gmail.com','HENRY ALBERTO CARVAJAL VALBUENA','1115186348');
INSERT INTO client (age,email,name,password) VALUES(32,'YOJANABARBOSA2912@GMAIL.COM','LILIA YOJANNA BARBOSA PICO','1121874401');
INSERT INTO client (age,email,name,password) VALUES(29,'matranetru@enayu.com','ANGEL DEJESUS GARCIA CASTILLO','1125351122');
INSERT INTO client (age,email,name,password) VALUES(31,'RANDYDCUELLO@GMAIL.COM','RANDY DARIEL DUEÑEZ CUELLO','1126706132');
INSERT INTO client (age,email,name,password) VALUES(67,'randydcuello@gmail.com','FOLGUER DUEÑEZ FAJARDO','91150852');
INSERT INTO client (age,email,name,password) VALUES(34,'wildonavila11@outlook.es','WILDON ALBEIRO AVILA VILORIA','1127591993');
INSERT INTO client (age,email,name,password) VALUES(40,'mertofolmo@enayu.com','JOSE DE LOS ANGELES SANDOVAL CONRADO','1129527055');
INSERT INTO client (age,email,name,password) VALUES(37,'JHONFVC1712@GMAIL.COM','JOHN FREDDY VIRGUEZ CERON','1130648180');
INSERT INTO client (age,email,name,password) VALUES(34,'mafergie19_@hotmail.com','MARIA FERNANDA CASTELLANOS QUILINDO','1130680328');
INSERT INTO client (age,email,name,password) VALUES(59,'rzo97893@zzrgg.com','LUIS CARLOS RODRIGUEZ ','11341218');